<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Lap_skripsi extends CI_Controller{
    function __construct()
    {
        parent::__construct();
        $this->load->model('Lap_skripsi_model');
    } 

    /*
     * Listing of lap_skripsi
     */
    function index()
    {
        $data['lap_skripsi'] = $this->Lap_skripsi_model->get_all_lap_skripsi();
        
        $data['_view'] = 'backend/lap_skripsi/index';
        $this->load->view('backend/layouts/main',$data);
    }

    /*
     * Adding a new lap_skripsi
     */
    function add()
    {   
        if(isset($_POST) && count($_POST) > 0)     
        {   
            $params = array(
				'nim' => $this->input->post('nim'),
				'judul_laporan' => $this->input->post('judul_laporan'),
				'jenis_laporan' => $this->input->post('jenis_laporan'),
				'tgl_upload' => $this->input->post('tgl_upload'),
				'dospem_1' => $this->input->post('dospem_1'),
				'dospem_2' => $this->input->post('dospem_2'),
				'kategori_laporan' => $this->input->post('kategori_laporan'),
				'upload_laporan' => $this->input->post('upload_laporan'),
				'notifikasi' => $this->input->post('notifikasi'),
            );
            
            $lap_skripsi_id = $this->Lap_skripsi_model->add_lap_skripsi($params);
            redirect('lap_skripsi/index');
        }
        else
        {            
            $data['_view'] = 'backend/lap_skripsi/add';
            $this->load->view('backend/layouts/main',$data);
        }
    }  

    /*
     * Editing a lap_skripsi
     */
    function edit($id_laporan)
    {   
        // check if the lap_skripsi exists before trying to edit it
        $data['lap_skripsi'] = $this->Lap_skripsi_model->get_lap_skripsi($id_laporan);
        
        if(isset($data['lap_skripsi']['id_laporan']))
        {
            if(isset($_POST) && count($_POST) > 0)     
            {   
                $params = array(
					'nim' => $this->input->post('nim'),
					'judul_laporan' => $this->input->post('judul_laporan'),
					'jenis_laporan' => $this->input->post('jenis_laporan'),
					'tgl_upload' => $this->input->post('tgl_upload'),
					'dospem_1' => $this->input->post('dospem_1'),
					'dospem_2' => $this->input->post('dospem_2'),
					'kategori_laporan' => $this->input->post('kategori_laporan'),
					'upload_laporan' => $this->input->post('upload_laporan'),
					'notifikasi' => $this->input->post('notifikasi'),
                );

                $this->Lap_skripsi_model->update_lap_skripsi($id_laporan,$params);            
                redirect('lap_skripsi/index');
            }
            else
            {
                $data['_view'] = 'backend/lap_skripsi/edit';
                $this->load->view('backend/layouts/main',$data);
            }
        }
        else
            show_error('The lap_skripsi you are trying to edit does not exist.');
    } 

    /*
     * Deleting lap_skripsi
     */
    function remove($id_laporan)
    {
        $lap_skripsi = $this->Lap_skripsi_model->get_lap_skripsi($id_laporan);

        // check if the lap_skripsi exists before trying to delete it
        if(isset($lap_skripsi['id_laporan']))
        {
            $this->Lap_skripsi_model->delete_lap_skripsi($id_laporan);
            redirect('lap_skripsi/index');
        }
        else
            show_error('The lap_skripsi you are trying to delete does not exist.');
    }
    
}
