<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Mahasiswa extends CI_Controller{
    function __construct()
    {
        parent::__construct();
        $this->load->model('Mahasiswa_model');
    } 

    /*
     * Listing of mahasiswa
     */
    function index()
    {
        $data['mahasiswa'] = $this->Mahasiswa_model->get_all_mahasiswa();
        
        $data['_view'] = 'backend/mahasiswa/index';
        $this->load->view('backend/layouts/main',$data);
    }

    /*
     * Adding a new mahasiswa
     */
    function add()
    {   
        if(isset($_POST) && count($_POST) > 0)     
        {   
            $params = array(
				'password' => $this->input->post('password'),
				'nama_mhs' => $this->input->post('nama_mhs'),
				'thn_angkatan' => $this->input->post('thn_angkatan'),
				'username' => $this->input->post('username'),
            );
            
            $mahasiswa_id = $this->Mahasiswa_model->add_mahasiswa($params);
            redirect('mahasiswa/index');
        }
        else
        {            
            $data['_view'] = 'backend/mahasiswa/add';
            $this->load->view('backend/layouts/main',$data);
        }
    }  

    /*
     * Editing a mahasiswa
     */
    function edit($nim)
    {   
        // check if the mahasiswa exists before trying to edit it
        $data['mahasiswa'] = $this->Mahasiswa_model->get_mahasiswa($nim);
        
        if(isset($data['mahasiswa']['nim']))
        {
            if(isset($_POST) && count($_POST) > 0)     
            {   
                $params = array(
					'password' => $this->input->post('password'),
					'nama_mhs' => $this->input->post('nama_mhs'),
					'thn_angkatan' => $this->input->post('thn_angkatan'),
					'username' => $this->input->post('username'),
                );

                $this->Mahasiswa_model->update_mahasiswa($nim,$params);            
                redirect('mahasiswa/index');
            }
            else
            {
                $data['_view'] = 'backend/mahasiswa/edit';
                $this->load->view('backend/layouts/main',$data);
            }
        }
        else
            show_error('The mahasiswa you are trying to edit does not exist.');
    } 

    /*
     * Deleting mahasiswa
     */
    function remove($nim)
    {
        $mahasiswa = $this->Mahasiswa_model->get_mahasiswa($nim);

        // check if the mahasiswa exists before trying to delete it
        if(isset($mahasiswa['nim']))
        {
            $this->Mahasiswa_model->delete_mahasiswa($nim);
            redirect('mahasiswa/index');
        }
        else
            show_error('The mahasiswa you are trying to delete does not exist.');
    }
    
}
