<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Lap_ta_model extends CI_Model
{
    function __construct()
    {
        parent::__construct();
    }
    
    /*
     * Get lap_ta by id_laporan
     */
    function get_lap_ta($id_laporan)
    {
        return $this->db->get_where('lap_ta',array('id_laporan'=>$id_laporan))->row_array();
    }

    function get_lap_ta_by_nim($nim)
    {
        return $this->db->get_where('lap_ta',array('nim'=>$nim))->row_array();
    }
        
    /*
     * Get all lap_ta
     */
    function get_all_lap_ta()
    {
        $this->db->order_by('id_laporan', 'desc');
        return $this->db->get('lap_ta')->result_array();
    }
        
    /*
     * function to add new lap_ta
     */
    function add_lap_ta($params)
    {
        $this->db->insert('lap_ta',$params);
        return $this->db->insert_id();
    }
    
    /*
     * function to update lap_ta
     */
    function update_lap_ta($id_laporan,$params)
    {
        $this->db->where('id_laporan',$id_laporan);
        return $this->db->update('lap_ta',$params);
    }
    
    /*
     * function to delete lap_ta
     */
    function delete_lap_ta($id_laporan)
    {
        return $this->db->delete('lap_ta',array('id_laporan'=>$id_laporan));
    }
}