<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Lap_kkn_model extends CI_Model
{
    function __construct()
    {
        parent::__construct();
    }
    
    /*
     * Get lap_kkn by id_laporan
     */
    function get_lap_kkn($id_laporan)
    {
        return $this->db->get_where('lap_kkn',array('id_laporan'=>$id_laporan))->row_array();
    }

    function get_lap_kkn_by_nim($nim)
    {
        return $this->db->get_where('lap_kkn',array('nim'=>$nim))->row_array();
    }
        
        
    /*
     * Get all lap_kkn
     */
    function get_all_lap_kkn()
    {
        $this->db->order_by('id_laporan', 'desc');
        return $this->db->get('lap_kkn')->result_array();
    }
        
    /*
     * function to add new lap_kkn
     */
    function add_lap_kkn($params)
    {
        $this->db->insert('lap_kkn',$params);
        return $this->db->insert_id();
    }
    
    /*
     * function to update lap_kkn
     */
    function update_lap_kkn($id_laporan,$params)
    {
        $this->db->where('id_laporan',$id_laporan);
        return $this->db->update('lap_kkn',$params);
    }
    
    /*
     * function to delete lap_kkn
     */
    function delete_lap_kkn($id_laporan)
    {
        return $this->db->delete('lap_kkn',array('id_laporan'=>$id_laporan));
    }
}
