<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Lap_skripsi_model extends CI_Model
{
    function __construct()
    {
        parent::__construct();
    }
    
    /*
     * Get lap_skripsi by id_laporan
     */
    function get_lap_skripsi($id_laporan)
    {
        return $this->db->get_where('lap_skripsi',array('id_laporan'=>$id_laporan))->row_array();
    }

    function get_lap_skripsi_by_nim($nim)
    {
        return $this->db->get_where('lap_skripsi',array('nim'=>$nim))->row_array();
    }

    function get_comments($nim)
    {
        $query = $this->db->query("SELECT k.komentar, d.nama_dosen, k.tglwaktu, l.judul_laporan, l.abstrak_laporan, l.tgl_upload, l.dospem_1, l.dospem_2, l.file, m.nama_mhs FROM komentar k, lap_skripsi l, dosen d, mahasiswa m
        WHERE d.id_dosen=k.iddosen AND k.idlaporan=l.id_laporan AND l.nim=m.nim AND m.nim='$nim' AND k.jenislaporan='skripsi' ORDER BY k.tglwaktu DESC");

        return $query;
    }
        
    /*
     * Get all lap_skripsi
     */
    function get_all_lap_skripsi()
    {
        $this->db->select('*');
        $this->db->from('lap_skripsi');
        $this->db->join('mahasiswa', 'mahasiswa.nim = lap_skripsi.nim');
        $this->db->order_by('id_laporan', 'desc');
        return $this->db->get()->result_array();
    }
        
    /*
     * function to add new lap_skripsi
     */
    function add_lap_skripsi($params)
    {
        $this->db->insert('lap_skripsi',$params);
        return $this->db->insert_id();
    }
    
    /*
     * function to update lap_skripsi
     */
    function update_lap_skripsi($id_laporan,$params)
    {
        $this->db->where('id_laporan',$id_laporan);
        return $this->db->update('lap_skripsi',$params);
    }
    
    /*
     * function to delete lap_skripsi
     */
    function delete_lap_skripsi($id_laporan)
    {
        return $this->db->delete('lap_skripsi',array('id_laporan'=>$id_laporan));
    }
}
